@startuml

top to bottom direction
skinparam packageStyle rectangle
skinparam LineThickness 2
skinparam ArrowThickness 2
skinparam nodesep 100
skinparam ranksep 80
skinparam splines polyline

together {
  class Χρήστης #lightblue
  class Ιδιοκτήτης #lightgreen
  class Ενοικιαστής #lightgreen
  class Συντονιστής #pink
}

together {
  class Αγγελία #lightyellow
  class Κατηγορία
  class Τοποθεσία
  class Ιστορικό
}

together {
  class Ενοικίαση #lightgray
  class ΧρονικήΠερίοδος
  class Πληρωμή
  class Μεταφορά
  class Αξιολόγηση
}

together {
  class Αναφορά
  class Μήνυμα
  class Ειδοποίηση
  class ΛίσταΑγαπημένων
}

together {
  class Σύγκριση
  class AIAssistant
  class PremiumPlan
  class Διανομέας
  class Τράπεζα
}

Ιδιοκτήτης --|> Χρήστης
Ενοικιαστής --|> Χρήστης
Ιδιοκτήτης "1" -- "*" Αγγελία : δημιουργεί
Ενοικιαστής "1" -- "*" Ενοικίαση : νοικιάζει
Αγγελία "1" -- "*" Ενοικίαση : έχει

Ενοικίαση "1" -- "1" ΧρονικήΠερίοδος : συμβαίνει σε
Αγγελία "*" -- "1" Αναφορά : μπορεί να αναφερθεί
Χρήστης "*" -- "*" Αναφορά : αναφέρει
Αναφορά "*" -- "1" Χρήστης : μπορεί να στοχεύσει
Συντονιστής "1" -- "*" Αναφορά : εξετάζει

Χρήστης "*" -- "*" Μήνυμα : στέλνει/λαμβάνει
Ενοικιαστής "1" -- "*" Σύγκριση : κάνει
Σύγκριση "*" -- "*" Αγγελία : περιλαμβάνει

Ενοικίαση "1" -- "1" Πληρωμή : έχει
Ενοικίαση "1" -- "1" Μεταφορά : έχει
Ενοικίαση "1" -- "1" Αξιολόγηση : λαμβάνει

Χρήστης "1" -- "*" Αξιολόγηση : γράφει
Χρήστης "*" -- "*" Αξιολόγηση : μπορεί να λάβει
Ιδιοκτήτης "1" -- "0..1" PremiumPlan : εγγράφεται σε
Συντονιστής "1" -- "*" Αγγελία : μπορεί να διαγράψει
Συντονιστής "1" -- "*" Χρήστης : μπορεί να απενεργοποιήσει

Αγγελία "*" -- "1" Κατηγορία : ανήκει σε
Χρήστης "1" -- "*" Τοποθεσία : έχει
Αγγελία "1" -- "1" Τοποθεσία : έχει
Μεταφορά "1" -- "1" Διανομέας : ανατίθεται σε
Πληρωμή "*" -- "1" Τράπεζα : επεξεργάζεται από
Σύγκριση "1" -- "1" AIAssistant : χρησιμοποιεί
Χρήστης "1" -- "*" Ειδοποίηση : λαμβάνει
Αγγελία "*" -- "1" Ιστορικό : μεταφέρεται σε
Ενοικιαστής "1" -- "1" ΛίσταΑγαπημένων : έχει
ΛίσταΑγαπημένων "*" -- "*" Αγγελία : περιέχει

@enduml
