@startuml
actor "Renter" as Renter
participant "Dashboard" as MainScreen
participant "ListingSelectionScreen" as ListingSelectionScreen
participant "ReviewScreen" as ReviewScreen
participant "ListingDetailScreen" as ListingDetailScreen
participant "Database" as DB

Renter -> MainScreen : reviewListing()
activate MainScreen

MainScreen -> DB : getOldRentListings()
activate DB
DB --> MainScreen : results
deactivate DB

MainScreen -> ListingSelectionScreen : showListingSelect()
deactivate MainScreen
activate ListingSelectionScreen

Renter -> ListingSelectionScreen : reviewListing()
ListingSelectionScreen -> ReviewScreen : showReviewForm()
deactivate ListingSelectionScreen
activate ReviewScreen

loop until successful submission or cancellation
    Renter -> ReviewScreen : fills form && clickConfirm()
    ReviewScreen -> ReviewScreen : checkReview()

    alt Επιτυχής έλεγχος περιεχομένου
        ReviewScreen -> DB : saveReview()
        activate DB
        deactivate DB

        ReviewScreen -> DB : attachReviewToListing()
        activate DB
        deactivate DB

        ReviewScreen -> ListingDetailScreen : showListingPage()
        deactivate ReviewScreen
    else Αποτυχής έλεγχος περιεχομένου
        ReviewScreen -> ReviewScreen : informUser()
    end
end

alt Ακύρωση από τον ενοικιαστή
    Renter -> ReviewScreen : exiting()
    activate ReviewScreen
    ReviewScreen -> MainScreen : showHomepage()
    deactivate ReviewScreen
    activate MainScreen
    deactivate MainScreen
end
@enduml
