@startuml
top to bottom direction
actor Ιδιοκτήτης

' Boundaries (Screens)
boundary "Αρχική Οθόνη" as B1
boundary "Οθόνη Προβολής Ιστορικού" as B2
boundary "Οθόνη Προβολής Ιστορικού με φόρμα" as B3
boundary "Οθόνη Πλήρους Περιγραφής Αγγελίας" as B4

' Controllers (Processes)
control "Ανακτά τις αγγελίες του ιδιοκτήτη" as C1
control "Φιλτράρει τα αποτελέσματα" as C2
control "Δημιουργεί τις λίστες των αποτελεσμάτων" as C3
control "Φορτωνει την οθόνη προβολής ιστορικού" as C4
control "Φορτωνει την φορμα τροποποίησης" as C5
control "Ελεγχει την φορμα τροποποίησης" as C6
control "Αποθηκευη προσωρινά την φορμα τροποποίησης" as C7
control "εμφανιζει μηνυμα επιβεβαίωσης" as C8
control "Τροποποιεί την κατάσταση της αγγελίας" as C9
control "Αποθηκευεθ την τροποποιημένη αγγελία" as C10
control "Φορτωνει τη οθονη της τροποποιημένης αγγελίας" as C11

control "Φορτωνει την αρχικη οθονη" as AC1
control "Δεν επιβεβαιωνει την τροποποίησης" as AC2
control "εμφανιζει ειδοπ λαθ" as AC3

' Entities
entity "Βάση Δεδομένων" as E1
entity "Αρχείο προσωρινής αποθήκευσης" as E2

' Actor Interactions
Ιδιοκτήτης --> B1 : Επιλέγει την προβολή του ιστορικού
Ιδιοκτήτης --> B2 : Επιλέγει επαναφορά ανενεργής αγγελίας

' Flow
B1 --> C1
C1 --> C2
C2 --> C3
C3 --> C4
C4 --> B2
B2 --> C5
C5 --> B3 : ALAZEI TA STEIXIA AGGELIAS
B3 --> C6
C6 --> C65
C65 --> C7
C7 --> E2
C7 --> C8
C8 --> C9
C9 --> C10
C10 --> C11
C11 --> B4

C6 --> AC2
AC2 --> AC3
AC3 --> C5

AC1 --> B1
B2 --> AC1
C8 --> AC1
C5 --> AC1

C1 --> E1

@enduml
